version: '3.3'

services:
  app: &app_base
    build: .
    command:
      [ "bash", "-c", "rm -f tmp/pids/server.pid; ./bin/rails server -b 0.0.0.0" ]
    env_file:
      - .env
    environment:
      EDITOR: "vim"
      POSTGRES_PASSWORD: "passwd"
    ports:
      - 3000:3000
    volumes:
      - .:/app
      - bundle:/usr/local/bundle
    depends_on:
      - db
      - spring
    tty: true
    stdin_open: true

  spring:
    <<: *app_base
    command:
      ["bundle", "exec", "spring", "server"]
    ports: []
    depends_on:
      - db
    tty: false
    stdin_open: false

  db:
    image: postgres:11
    volumes:
      - pg_data:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: "passwd"

volumes:
  bundle:
  pg_data:
